name: uv
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install clangd
        run: |
          sudo apt update
          sudo apt -y --no-install-recommends install clangd

      - name: Lint project
        run: bash ./scripts/lint.sh

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Build project
        run: bash ./scripts/build.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: executable
          path: ./build/new_project
          retention-days: 3

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: executable

      - name: Fix permission
        run: chmod +x ./new_project

      - name: Test project
        run: ./new_project
